# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConsumerProfile',
        ),
    ]
