# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170703_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstype',
            options={'verbose_name': 'Business Type', 'verbose_name_plural': 'Business Types'},
        ),
        migrations.AddField(
            model_name='businesses',
            name='tips_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
