# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_businesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='businesses',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Businesses'),
        ),
    ]
