# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170401_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesses',
            name='state',
        ),
        migrations.AddField(
            model_name='businesses',
            name='state_province',
            field=models.CharField(max_length=30, null=True, verbose_name='State'),
        ),
    ]
