# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Businesses'),
        ),
    ]
