# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170425_1804'),
        ('accounts', '0013_auto_20170420_2010'),
    ]

    operations = [
    ]
