# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20170427_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='rev_share_perc',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10, verbose_name='Revenue Share %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesses',
            name='zipcode',
            field=models.CharField(default=10012, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesses',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
