# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170427_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesses',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='businesses',
            name='owner',
            field=models.BooleanField(default=False, verbose_name='User is Business Owner'),
        ),
        migrations.AddField(
            model_name='businesses',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
