# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170429_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesses',
            name='owner',
        ),
    ]
