# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_businesses_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Businesses'),
        ),
    ]
