# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appconfig', '0002_auto_20170505_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConfig',
            fields=[
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical App Config',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'App Config', 'verbose_name_plural': 'App Config'},
        ),
    ]
