# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business_Balance',
            new_name='BusinessBalance',
        ),
        migrations.RenameModel(
            old_name='Customer_Balance',
            new_name='CustomerBalance',
        ),
        migrations.RenameModel(
            old_name='Process_Payment',
            new_name='ProcessPayment',
        ),
    ]
