# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 03:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20170425_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbalance',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
