# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 03:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20170425_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processpayment',
            name='fixed_comm_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fixed Commission Amt'),
        ),
        migrations.AlterField(
            model_name='processpayment',
            name='payment_amt',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Purchase Amount'),
        ),
        migrations.AlterField(
            model_name='processpayment',
            name='var_comm_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Variable Commission Amt'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='fixed_fee_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fixed Fee Amt'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_amt',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Purchase Amount'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='var_fee_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Variable Fee Amt'),
        ),
    ]
