# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20170425_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='processpayment',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
