# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_processpayment_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessbalance',
            old_name='reason',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='customerbalance',
            old_name='reason',
            new_name='comments',
        ),
    ]
