# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20170426_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='refund',
        ),
    ]
