# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_purchase_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessbalance',
            name='business',
        ),
        migrations.RemoveField(
            model_name='customerbalance',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='processpayment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='business',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='customer',
        ),
        migrations.DeleteModel(
            name='BusinessBalance',
        ),
        migrations.DeleteModel(
            name='CustomerBalance',
        ),
        migrations.DeleteModel(
            name='ProcessPayment',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
