# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_customerbalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerbalance',
            options={'verbose_name': 'Customer Balance', 'verbose_name_plural': 'Customer Balances'},
        ),
    ]
